#!/bin/sh

base="192.168.0"
echo "\033[1;37mDevices:\033[0m"
scan_redes=$(nmap -sP $base".1/24" | grep $base | awk '{ print $5 }')
for dev in $scan_redes;
do
  echo " --> \033[1;32m$dev\033[0m"
done
echo
for dev in $scan_redes;
do
  echo "\033[1;37m$dev\033[0m [\033[1;31mServices\033[0m] {"
  nmap $dev | grep 'open' | awk '{split($1,a,"/"); print "\t::[\033[1;32m" $3 "\033[0m] -> (\033[1;33m" a[1] "\033[0m)"}'
  echo "}"
done
