#!/bin/sh

ip=$1
for dev in $ip;
do
  echo "\033[1;37m$dev\033[0m [\033[1;31mServices\033[0m] {"
  nmap $dev | grep 'open' | awk '{split($1,a,"/"); print "\t::[\033[1;32m" $3 "\033[0m] -> (\033[1;33m" a[1] "\033[0m)"}'
  echo "}"
done
